### ISSUE TITLE
Callouts prevent rendering block

### ISSUE THREAD

**Issue by moimael** [asciidoctor/atom-asciidoc-preview#111]
Hi,

When I use callouts, my preview won't render the block content under the callouts. It render well when I use the command line.

Ex:

```
=== Packages list
----
alinto-combine-3-RELEASE.noarch.rpm
alinto-factory-2.7-SP2.noarch.rpm  # <1>
alinto-factory-ws-2.7-RELEASE.noarch.rpm  # <1>
alinto-milter-1.2.1-RELEASE.noarch.rpm
alinto-milter-rules-1.2.1-RELEASE.noarch.rpm
alinto-mobile-1.5-SP4.noarch.rpm
alinto-webdav-3.5-RELEASE.noarch.rpm
mod_jk-ap22-1.2.40-3.el6.x86_64.rpm
----
<1> Updated package compared to previous release
```

What is rendered : 
```
=== Packages list
----
alinto-combine-3-RELEASE.noarch.rpm
alinto-factory-2.7-SP2.noarch.rpm
----
<1> Updated package compared to previous release
```

**Comment by mojavelinux** [comment]
This problem seems to go away if you add `[source]` to the block. If I observe the source of the output, I see that each line is wrapped in a div. Without `[source]`, only two lines get shown. With `[source]`, all the lines appear. So somewhere before the text is put into the preview, lines are being dropped when it's a listing or literal block, but not a source block.

If I try with the Asciidoctor.js directly, everything works as expected.

**Comment by mojavelinux** [comment]
Thanks for reporting this issue!

**Comment by ldez** [comment]
This issue was fixed in previous version.

![capture du 2016-09-10 14-45-23](https://cloud.githubusercontent.com/assets/5674651/18410511/3d2eec9c-7765-11e6-881e-876f1d54ba51.png)
