### ISSUE TITLE
XML closing tag U (</) disappears in preview

### ISSUE THREAD

**Issue by len1980** [asciidoctor/atom-asciidoc-preview#241]
## Description

XML closing tag U (</) disappears in preview

- Atom version:1.17.2
- OS:max osx sierra
- `asciidoc-preview` version:2.10.1
- `language-asciidoc` version:1.10.1

## Screenshots
using asciidoc preview

<img width="600" alt="2017-05-31 10 06 15" src="https://cloud.githubusercontent.com/assets/27874513/26611365/d6e07138-45e8-11e7-871e-0b04f76d94d9.png">

using asciidocFX
![2017-05-31 10 08 08](https://cloud.githubusercontent.com/assets/27874513/26611449/5978be52-45e9-11e7-8fa3-0d96186d7c62.png)

## Syntax example
```adoc
[source,xml]
----
<profiles>
	<function> </function>
	<first_name></first_name>
	<last_name></last_name>
	<e-mail></e-mail>
	<company_name></company_name>
</profiles>
----
```

**Comment by mojavelinux** [comment]
The problem is that HTML special characters are not being escaped (e.g., `<` replaced with `&lt;`). This problem got introduced when the switch to highlights for source highlighting was made.

Here's the line that needs to be changed:

https://github.com/asciidoctor/atom-asciidoc-preview/blob/5f44d0f65f22739b16234226bf533249ad963eb7/lib/highlights.coffee#L63

We need something like:

```
value.replace('&', '&amp;').replace('<', '&lt;')
```

(technically, there's no need to replace >.

**Comment by ldez** [comment]
we can replace all html entities but it's not a good idea because this is apply for all languages.

**Comment by ldez** [comment]
I'm stupid: it's only apply in pre-render...

**Comment by mojavelinux** [comment]
You are correct that this is about safely encoding characters that are put into an HTML page, so the language of the source block is irrelevant. You aren't correct that you are stupid ;) Exactly the opposite.
