### ISSUE TITLE
Preferences : there is two entries for the option showToc

### ISSUE THREAD

**Issue by anthonny** [asciidoctor/atom-asciidoc-preview#29]
We must remove `showToc` and keep `showTableOfContent`.

Change : 
```
atom.workspaceView.command 'asciidoc-preview:toggle-show-toc', ->
      atom.config.toggle('asciidoc-preview.showToc')
```

by
```
atom.workspaceView.command 'asciidoc-preview:toggle-show-toc', ->
      atom.config.toggle('asciidoc-preview.showTableOfContent')
```

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/2006548/3340078/d9a0a076-f877-11e3-8dce-e84c9abc734a.png)

Thx to @YannDanthu for reporting

**Comment by PierreR** [comment]
The `TOC` is only previewed if  I insert a `>` (quote text) between the document title and the first section ...

I would expect the `toc` to be previewed whenever I use the `::toc::` attribute.

**Comment by abelsromero** [comment]
Thanks for the reminder, this should definitely be closed.

The use of TOC in the preview is a bit confusing, I know it first-hand. You can get more information in the issue about the the PR you mention #99.

Long story, short...Current relased version of the preview shows the TOC in `preamble` mode, that is, under the preamble. And what's the preamble? Just any text (Asciidoc paragraph, admonition, etc.) between the the document title and the fist section.
Btw, since the preview is build in embedded mode, the `:toc:` attribute in the document is not used...forget about right or left options :/

The PR adressed this offering all availlable options in the embedded mode.

**Comment by mojavelinux** [comment]
Can we mark the milestone in which this issue was fixed?

**Comment by ldez** [comment]
Regrettably I don't know the milestone.

**Comment by mojavelinux** [comment]
I got it. It's 0.6.0.
