### ISSUE TITLE
Callouts not drawn in code piece

### ISSUE THREAD

**Issue by alefragnani** [asciidoctor/atom-asciidoc-preview#72]
Hi

When I use callouts, the preview does not shows correctly in the code section. I used the example provided in [Asciidoctor Syntax Quick Reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code), and the print is below:

![print-asciidoc-preview-callout](https://cloud.githubusercontent.com/assets/3781424/7171912/6c6f52de-e3b5-11e4-9221-f5057e1a6315.png)

Thanks

**Comment by mojavelinux** [comment]
This is known and a tough issue to solve. The problem is that the Atom syntax highlighter doesn't know about callouts in the source code. We would need to decorate the Atom code that handles syntax highlighting and deal with them specially just like what is done in Asciidoctor core. Specifically, the following things happen:

1. Callouts are removed from the source and stored in a replacement table by line number
2. Syntax highlighting proceeds
3. Callouts are restored in the original location, this time using special HTML that is styled as callout numbers (we could opt to use Unicode circled numbers in this display)

**Comment by mojavelinux** [comment]
Slight correction to my comment. It's highlight.js that we need to decorate. If it provides hooks before and after syntax highlight, we can do step 1 and 3 listed above. This would benefit all uses of Asciidoctor + highlight.js.

**Comment by ldez** [comment]
Now the grammar manage callouts in code block.

Consider using the Ruby comment syntax in Ruby code provide a better grammar render:

```adoc
[source,ruby]
----
require 'sinatra' # <1>

get '/hi' do # <2>
  "Hello World!" # <3>
end
----
<1> Library import
<2> URL mapping
<3> Content for response
```

![capture du 2016-05-23 22-17-48](https://cloud.githubusercontent.com/assets/5674651/15483276/348704ee-2134-11e6-900c-b53723d3a661.png)

**Comment by mojavelinux** [comment]
Nice!
