### ISSUE TITLE
Include macro doesn't work

### ISSUE THREAD

**Issue by yfain** [asciidoctor/atom-asciidoc-preview#84]
Asciidoc include macro is not processed properly.  

![this](https://cloud.githubusercontent.com/assets/2254842/7440822/490c1ae8-f099-11e4-9fb6-9a188483afab.png)

I checked the settings of this package, but there is nothing to turn on/off. Tried to move the code directory one level down, but it didn't help. This is a showstopper for me unless there is a quick solution to this problem.

**Comment by mojavelinux** [comment]
Isn't this just a matter of setting the safe mode? (Recommended value is unsafe for this context). Check the option page for the plugin.

**Comment by mojavelinux** [comment]
Btw, this would be good to document in the README (one way or the other).

**Comment by yfain** [comment]
I tried both unsafe and UNSAFE in settings of this package. With these settings the preview simply doesn't work. It shows the never ending message Loading AsciiDoc...

I switched back from Atom to Sublime Text with the builder that invokes asciidoctor - includes work fine there.

**Comment by mojavelinux** [comment]
I can confirm that if I set the safe mode to value `unsafe`, an include in an arbitrary directory above the directory of a current file (the most "insecure" case) works for me.

> It shows the never ending message Loading AsciiDoc...

That sounds like a different problem.

Could you point to an example file or project that demonstrates this problem so that we can debug? Thanks!

**Comment by mojavelinux** [comment]
I still think that we should clearly document the affect safe mode has on includes in the README, with a reference to the section in the Asciidoctor user manual for more information.

**Comment by yfain** [comment]
Yes, the safe mode need to be documented. I figured out why the preview was giving that never ending message. I put unsafe instead of Default: unsafe. My bad, but it shouldn't be hanging anyway.

But the include still doesn't work. Please try to open the CTOschool.adoc from this zip file: http://bit.ly/1IzYKdK. It has one include to the HelloWorld.java that is not shown in the preview. Thanks.

**Comment by mojavelinux** [comment]
Thanks for providing the example, @yfain! We'll have a look.

**Comment by mojavelinux** [comment]
Aha! The problem is the `source-highlighter` setting. The value of `pygments` is causing Asciidoctor.js to crash. There is a special way we need to deal with this setting to avoid it from messing up rendering. I'll follow up with a separate issue to get that ironed out so it doesn't crash Asciidoctor.js.

In the meantime, you can:

a. comment out this attribute or
b. hide it behind a conditional

```
ifndef::platform-opal[:source-highlighter: pygments]
```

Either way, that should resolve your rendering issue.

**Comment by mojavelinux** [comment]
Reported as #88. I believe this issue can now be closed.

**Comment by yfain** [comment]
Removing the line :source-highlighter: pygments didn't help with the include issue.

**Comment by mojavelinux** [comment]
>  I put unsafe instead of Default: unsafe.

The value in the box should be, verbatim:

```
unsafe
```

(the configuration setting itself should be a select menu, not a text field).

Does that make it work?

Make sure you have the latest atom and the latest plugin. What version of the plugin do you have? It should be 0.4.3.

Are you on Windows, by chance?

**Comment by yfain** [comment]
Thank you, Dan. The unsafe helped. I'm on MAC.

**Comment by mojavelinux** [comment]
Perfect!
