### ISSUE TITLE
Toc shows when adding an single-line admonition under the title

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/atom-asciidoc-preview#99]
Even when the “Show Toc” option is enable, it does not appear on my editor. However this is not the issue, the real thing is that when I insert a single-line admonition right under the title, a toc is rendered under it.

I have tested this with _Asciidoctor.js Live Preview_ in Chrome and converting the same document with AsciidoctorJ and this issue only appears in the Atom.io preview.

Here is what I get

![ascii_issue](https://cloud.githubusercontent.com/assets/5781153/8874572/7a3c346c-3212-11e5-9852-e2c579605728.PNG)

and here is the sample document.

```
= Notes
:icons: font

NOTE: this is a note

== First section

* Some information
* Some more information

== Second section

* Some numbered information
* Some more numbered information


== The third one

This is a simple paragraph

```

**Comment by mojavelinux** [comment]
> when I insert a single-line admonition right under the title, a toc is rendered under it.

This is the expected behavior, which I'll explain. Right now, the Atom editor treats the toc control as a switch, either on or off. When it's on, it is set to "preamble". A premable toc is inserted directly below the preamble. When you start your document with an admonition block, that block becomes the preamble block. Therefore, the placement of the toc is logical.

The real problem is that toc is not a boolean switch. Instead, it is an enumeration. There are three possible values that are relevant in the embeddable HTML output (the output that is shown in the preview window).

* (off)
* preamble
* macro

The macro option is probably what you want as it will allow you to place the toc exactly where you want it to appear.

We probably should add the option for the toc to appear directly below the title in the embeddable mode if the value is "auto" (or blank).

**Comment by abelsromero** [comment]
Much clearer now, thanks. But after that explanation I have another doubt.

You mentioned ...

> There are three possible values that are relevant in the embeddable HTML

but in the documentation (http://asciidoctor.org/docs/user-manual/#table-of-contents-summary) this options appear mixed between `:toc:` and `:toc-placement:`.
Also, seeing this, https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/worker.coffee#L12, I would say it sets `:toc:`, but there's no preamble option for :toc:.
So, my doubt is, what is really setting the "Toggle Table of Contents" option?

**Comment by mojavelinux** [comment]
The line you are looking for is here:

https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/renderer.coffee#L20

`toc-placement` is mostly a deprecated attribute. In Asciidoctor, we prefer the use of the `toc` attribute to control the placement (as well as whether it's enabled).

Under the covers, the `toc` attribute sets the `toc-placement`. The latter is what gets used in the converter. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L701-L714.

**Comment by mojavelinux** [comment]
Perhaps it's better to say that `toc-placement` is an internal attribute.

**Comment by abelsromero** [comment]
Again, thanks for the info.

Just as a final comment, maybe allowing a select option to choose between the different possibilities like right or left would be a solution not only to avoid ambiguity, but to facilitate learning the different options.

wdyt?

**Comment by mojavelinux** [comment]
Agreed.
